/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        wv: {
          black: '#0a090b',
          ink: '#000000',
          charcoal: '#18161b',
          surface: '#242129',
          ivory: '#fbf6f0',
          warmwhite: '#faf7f2',
          paper: '#fbf6f0',
          dirtywhite: '#ebe3d5',
          dust: '#948e8c',
          grape: '#6A1A4C',
          glisteninggrape: '#6A1A4C',
          dustyrose: '#6A1A4C',
          dustypink: '#6A1A4C',
          oldpink: '#6A1A4C',
          pink: '#6A1A4C',
          // Purged all red/wine - remapped safely to stark black and glistening grape
          oxblood: '#000000',
          wine: '#000000',
          burgundy: '#18161b',
          blood: '#000000',
          red: '#000000',
          cobalt: '#1b3bb6',
          royal: '#10257e',
          orange: '#cf552a',
          terracotta: '#bf502b',
          mustard: '#cfa030',
          plum: '#18161b',
          purple: '#000000',
          border: '#000000',
        }
      },
      fontFamily: {
        brand: ['"Meie Script"', 'cursive'],
        display: ['Fraunces', 'Newsreader', 'serif'],
        fun: ['Fraunces', 'serif'],
        shrikhand: ['Shrikhand', 'cursive'],
        cinzel: ['Cinzel', 'serif'],
        arthouse: ['"Instrument Serif"', 'Italiana', 'serif'],
        instrument: ['"Instrument Serif"', 'serif'],
        italiana: ['Italiana', 'serif'],
        scribble: ['Caveat', 'cursive'],
        handwriting: ['Caveat', 'cursive'],
        serif: ['Newsreader', 'Georgia', 'serif'],
        sans: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        mono: ['Space Mono', 'Courier New', 'monospace'],
      },
      boxShadow: {
        'none': '0 0 #0000',
        'editorial': '0 0 #0000',
        'editorial-bold': '0 0 #0000',
        'editorial-rose': '0 0 #0000',
        'editorial-wine': '0 0 #0000',
        'editorial-cobalt': '0 0 #0000',
        'editorial-mustard': '0 0 #0000',
        'editorial-ivory': '0 0 #0000',
      },
    },
  },
  plugins: [],
};
